### ISSUE TITLE
Add practical 'How to set this up in Google Content Experiments' md file

### ISSUE THREAD

**Issue by iteles** [iteles/learn-multivariate-testing#13]
And link to it in the readme. 
Use dwyl as example?

**Comment by nelsonic** [comment]
:+1:

**Comment by iteles** [comment]
- [x] Add these link to the practical tutorial - Tips to improve your testing: http://marketingland.com/12-tips-to-take-your-ab-multivariate-testing-to-the-next-level-50249 also for interpreting your results section: http://www.optimizeandprophesize.com/jonathan_mendezs_blog/2008/05/multivariate-te.html and https://econsultancy.com/blog/6740-what-your-mother-never-taught-you-about-multivariate-testing/

**Comment by iteles** [comment]
This has been started here: https://github.com/iteles/learn-google-content-experiments

**Comment by iteles** [comment]
This is being dealt with in a separate repo to encapsulate the practical task which is specific to Google Content Experiments: https://github.com/iteles/learn-google-content-experiments

The current content of _this_ repo applies broadly to testing with any tool.
